### ISSUE TITLE
Sample rate gets rounded to thousands

### ISSUE THREAD

**Issue by Kolyunya** [TinkoffCreditSystems/tinkoff-speech-api-examples#4] opened 2019-07-31 19:06 UTC
I'm trying to recognize an audio file with a sample rate of `22050 hz`. I pass the correct value of the corresponding parameter: `--rate 22050` but get an error which says that the sample rate is configured to `22000 hz` which is not true.

```sh
#! /bin/bash

source "./sh/env.sh"
cat $1 | \
    python3 -m recognize_stream --host stt.tinkoff.ru --port 443 \
    --rate 22050 --num_channels 2 --encoding MPEG_AUDIO \
    --chunk_size 8192 --api_key $STT_TEST_API_KEY --secret_key $STT_TEST_SECRET_KEY
```

> Audio header reports sample rate of 22050 hz, but recognition_config.sample_rate_herts = 22000

The same problem appears with the `44100 hz`. Seems like the sample rate get rounded to thousands somewhere while being passed to the API.

**Comment by penguin138** [comment] 2019-08-01 19:03
Hi. This seems to be related to the fact that internally we resample audio from its original samplerate to the samplerate supported by acoustic model. Resampler that we use only supports handful of samplerate conversion modes, all of which assume that we can round samplerate to thousands, because there is actually almost no difference between 22050 or 22000 samplerate or between 44100 and 44000 from resampling standpoint. The error was caused by an incorrect samplerate check before resampling would occur (we forgot to account for rounding). The error is fixed now, I'll be updating our backend in a few hours. Thanks for reporting this!

**Comment by penguin138** [comment] 2019-08-03 16:58
Sorry for the delay. Finally, I've updated our backend, now samplerates 44100, 22050 and similar should work.

**Comment by standy66** [comment] 2019-08-07 15:19
Should we close this issue?

**Closed as completed** 2019-10-28 19:55 UTC
Labels: bug
